monolog:
    handlers:
        # exception log
        exception:
            type: stream
            path: '%kernel.logs_dir%/exception.log'
            level: error
            channels: ['!event']

# dev env log
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
