name: PHP-CodeSniffer

# specify when the workflow should be triggered
on:
  push:
    branches:
      - main
      - dev

# define the jobs to be executed in the workflow
jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install dependencies
      run: composer install --no-interaction --no-progress --no-suggest

    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs
